config/routes.rb
Zeprj::Application.routes.draw do
  root :to => 'home#welcomes', as: 'welcomes'
  get 'welcome', :to => 'home#welcome', as: 'welcome'
  get 'signin', :to => 'sessions#new', as: 'signin'
  get 'signout', :to => 'sessions#destroy', as: 'signout'
  get 'signup', :to => 'accounts#new', as: 'signup'

  get 'warehouse/home', :to => 'warehouse#home'

  resources :accounts
  resources :sessions
  resources :products
  resources :merchants

  get 'warehouses/available', :to => 'warehouses#available'
  get 'product_summaries/import_availables', :to => 'product_summaries#import_availables'
  get 'productSummaries/import_availables', :to => 'product_summaries#import_availables'

  get 'areas/showAllCustomers', :to => 'areas#showAllCustomers'
  get 'areas/showAllCustomers/:id', :to => 'areas#showAllCustomers'
  get 'warehouses/search', :to => 'warehouses#search'
  get 'product_summaries/search', :to => 'product_summaries#search'
  get 'orders/bill_code', :to => 'orders#bill_code'

  resources :gera_accounts
  resources :gera_areas
  resources :gera_customers
  resources :areas
  resources :agencies
  resources :merchant_accounts
  resources :customers

  resources :branches
  resources :warehouses
  resources :skulls
  resources :providers
  resources :product_summaries
  resources :metro_summaries

  resources :imports
  resources :deliveries
  resources :exports
  resources :export_details
  resources :inventories
  resources :inventory_details
  resources :orders
  resources :order_details
  resources :returns
  resources :return_details
  resources :temp_products
  resources :temp_inventory_details

  resources :roles
  resources :role_permissions
  resources :merchant_account_roles
  resources :merchant_account_permissions
  resources :merchant_account_permission_details
  resources :permissions
  resources :permission_details

  resources :mackay_profiles
  resources :mackay_families
  resources :mackay_educations
  resources :mackay_personals
  resources :mackay_children
  resources :mackay_life_styles
  resources :mackay_hobbies
  resources :mackay_careers
  resources :mackay_and_companies

  resources "merchantAccounts", :controller => :merchant_accounts, :as => :merchant_accounts
  resources "productSummaries", :controller => :product_summaries, :as => :product_summaries

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :warehouses
  has_many :orders
  has_many :merchant_accounts

  belongs_to :merchant

  after_create :create_warehouse
  before_destroy :destroy_branch

  private
  def create_warehouse
    if(Merchant.find(self.merchant_id))
    end
    #Tao Warehouse sau khi tao Branch
    Warehouse.create!({merchant_id:self.merchant_id, branch_id:self.id, name:self.name})
  end

  def destroy_branch
    #Bat loi co skull Product va ProductSummary
    if(Warehouse.find_by_branch_id(self.id)!=nil)

    end

  end
end

app/controllers/branches_controller.rb
class BranchesController < MerchantApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.where(merchant_id: current_merchant_account.merchant_id)
    respond_to do |format|
      format.html
      format.json { render :json => @branches }
    end
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render :json => @branch }
    end
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)
    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render action: 'show', status: :created, location: @branch }
      else
        format.html { render action: 'new' }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:merchant_id, :name)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= simple_form_for(@branch) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :merchant_id %>

    <%= f.input :name %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing branch</h1>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<h1>Listing branches</h1>

<table>
  <thead>
    <tr>
      <th>Merchant</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.merchant_id %></td>
        <td><%= branch.name %></td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Branch', new_branch_path %>

app/views/branches/new.html.erb
<h1>New branch</h1>

<%= render 'form' %>

<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Merchant:</strong>
  <%= @branch.merchant_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @branch.name %>
</p>

<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>