config/routes.rb
Zeprj::Application.routes.draw do
  root :to => 'home#welcomes', as: 'welcomes'
  get 'welcome', :to => 'home#welcome', as: 'welcome'
  get 'signin', :to => 'sessions#new', as: 'signin'
  get 'signout', :to => 'sessions#destroy', as: 'signout'
  get 'signup', :to => 'accounts#new', as: 'signup'

  get 'warehouse/home', :to => 'warehouse#home'

  resources :accounts
  resources :sessions
  resources :products
  resources :merchants

  get 'warehouses/available', :to => 'warehouses#available'
  get 'product_summaries/import_availables', :to => 'product_summaries#import_availables'
  get 'productSummaries/import_availables', :to => 'product_summaries#import_availables'

  get 'areas/showAllCustomers', :to => 'areas#showAllCustomers'
  get 'areas/showAllCustomers/:id', :to => 'areas#showAllCustomers'
  get 'warehouses/search', :to => 'warehouses#search'
  get 'product_summaries/search', :to => 'product_summaries#search'
  get 'orders/bill_code', :to => 'orders#bill_code'

  resources :gera_accounts
  resources :gera_areas
  resources :gera_customers
  resources :areas
  resources :agencies
  resources :merchant_accounts
  resources :customers

  resources :branches
  resources :warehouses
  resources :skulls
  resources :providers
  resources :product_summaries
  resources :metro_summaries

  resources :imports
  resources :deliveries
  resources :exports
  resources :export_details
  resources :inventories
  resources :inventory_details
  resources :orders
  resources :order_details
  resources :returns
  resources :return_details
  resources :temp_products
  resources :temp_inventory_details

  resources :roles
  resources :role_permissions
  resources :merchant_account_roles
  resources :merchant_account_permissions
  resources :merchant_account_permission_details
  resources :permissions
  resources :permission_details

  resources :mackay_profiles
  resources :mackay_families
  resources :mackay_educations
  resources :mackay_personals
  resources :mackay_children
  resources :mackay_life_styles
  resources :mackay_hobbies
  resources :mackay_careers
  resources :mackay_and_companies

  resources "merchantAccounts", :controller => :merchant_accounts, :as => :merchant_accounts
  resources "productSummaries", :controller => :product_summaries, :as => :product_summaries

end

app/models/merchant_account_role.rb
class MerchantAccountRole < ActiveRecord::Base

  belongs_to :role
  belongs_to :merchant_account


end

app/controllers/merchant_account_roles_controller.rb
class MerchantAccountRolesController < ApplicationController
  before_action :set_merchant_account_role, only: [:show, :edit, :update, :destroy]

  # GET /merchant_account_roles
  # GET /merchant_account_roles.json
  def index
    @merchant_account_roles = MerchantAccountRole.all
  end

  # GET /merchant_account_roles/1
  # GET /merchant_account_roles/1.json
  def show
  end

  # GET /merchant_account_roles/new
  def new
    @merchant_account_role = MerchantAccountRole.new
  end

  # GET /merchant_account_roles/1/edit
  def edit
  end

  # POST /merchant_account_roles
  # POST /merchant_account_roles.json
  def create
    @merchant_account_role = MerchantAccountRole.new(merchant_account_role_params)
    update_merchant_account_permission_detail_by_merchant_account_role

    respond_to do |format|
      if @merchant_account_role.save
        format.html { redirect_to @merchant_account_role, notice: 'Merchant account role was successfully created.' }
        format.json { render action: 'show', status: :created, location: @merchant_account_role }
      else
        format.html { render action: 'new' }
        format.json { render json: @merchant_account_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchant_account_roles/1
  # PATCH/PUT /merchant_account_roles/1.json
  def update
    #cập nhật phân quầy
    @merchant_account_role.attributes =(merchant_account_role_params)
    update_merchant_account_permission_detail_by_merchant_account_role
    respond_to do |format|
      if @merchant_account_role.save()
        format.html { redirect_to @merchant_account_role, notice: 'Merchant account role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @merchant_account_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchant_account_roles/1
  # DELETE /merchant_account_roles/1.json
  def destroy
    @merchant_account_role.destroy
    respond_to do |format|
      format.html { redirect_to merchant_account_roles_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_merchant_account_role
    @merchant_account_role = MerchantAccountRole.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def merchant_account_role_params
    params.require(:merchant_account_role).permit(:merchant_account_id, :role_id, :permission_text)
  end

  def update_merchant_account_permission_detail_by_merchant_account_role
    current_permission = Permission.all
    a=[]
    RolePermission.where(role_id:@merchant_account_role.role_id).each do |role_permission|
      a= a + [current_permission.find(role_permission.permission_id).permission_key]
    end
    @merchant_account_role.permission_text = a.join(',')
  end

end

app/helpers/merchant_account_roles_helper.rb
module MerchantAccountRolesHelper
end

app/views/merchant_account_roles/_form.html.haml
= form_for @merchant_account_role do |f|
  - if @merchant_account_role.errors.any?
    #error_explanation
      %h2= "#{pluralize(@merchant_account_role.errors.count, "error")} prohibited this merchant_account_role from being saved:"
      %ul
        - @merchant_account_role.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :merchant_account_id
    = f.number_field :merchant_account_id
  .field
    = f.label :role_id
    = f.number_field :role_id
  .field
    = f.label :permission_text
    = f.text_area :permission_text
  .actions
    = f.submit 'Save'

app/views/merchant_account_roles/edit.html.haml
%h1 Editing merchant_account_role

= render 'form'

= link_to 'Show', @merchant_account_role
\|
= link_to 'Back', merchant_account_roles_path

app/views/merchant_account_roles/index.html.haml
%h1 Listing merchant_account_roles

%table
  %tr
    %th Merchant account
    %th Role
    %th Permission text
    %th
    %th
    %th

  - @merchant_account_roles.each do |merchant_account_role|
    %tr
      %td= merchant_account_role.merchant_account_id
      %td= merchant_account_role.role_id
      %td= merchant_account_role.permission_text
      %td= link_to 'Show', merchant_account_role
      %td= link_to 'Edit', edit_merchant_account_role_path(merchant_account_role)
      %td= link_to 'Destroy', merchant_account_role, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Merchant account role', new_merchant_account_role_path

app/views/merchant_account_roles/new.html.haml
%h1 New merchant_account_role

= render 'form'

= link_to 'Back', merchant_account_roles_path

app/views/merchant_account_roles/show.html.haml
%p#notice= notice

%p
  %b Merchant account:
  = @merchant_account_role.merchant_account_id
%p
  %b Role:
  = @merchant_account_role.role_id
%p
  %b Permission text:
  = @merchant_account_role.permission_text

= link_to 'Edit', edit_merchant_account_role_path(@merchant_account_role)
\|
= link_to 'Back', merchant_account_roles_path