config/routes.rb
Zeprj::Application.routes.draw do
  root :to => 'home#welcomes', as: 'welcomes'
  get 'welcome', :to => 'home#welcome', as: 'welcome'
  get 'signin', :to => 'sessions#new', as: 'signin'
  get 'signout', :to => 'sessions#destroy', as: 'signout'
  get 'signup', :to => 'accounts#new', as: 'signup'

  get 'warehouse/home', :to => 'warehouse#home'

  resources :accounts
  resources :sessions
  resources :products
  resources :merchants

  get 'warehouses/available', :to => 'warehouses#available'
  get 'product_summaries/import_availables', :to => 'product_summaries#import_availables'
  get 'productSummaries/import_availables', :to => 'product_summaries#import_availables'

  get 'areas/showAllCustomers', :to => 'areas#showAllCustomers'
  get 'areas/showAllCustomers/:id', :to => 'areas#showAllCustomers'
  get 'warehouses/search', :to => 'warehouses#search'
  get 'product_summaries/search', :to => 'product_summaries#search'
  get 'orders/bill_code', :to => 'orders#bill_code'

  resources :gera_accounts
  resources :gera_areas
  resources :gera_customers
  resources :areas
  resources :agencies
  resources :merchant_accounts
  resources :customers

  resources :branches
  resources :warehouses
  resources :skulls
  resources :providers
  resources :product_summaries
  resources :metro_summaries

  resources :imports
  resources :deliveries
  resources :exports
  resources :export_details
  resources :inventories
  resources :inventory_details
  resources :orders
  resources :order_details
  resources :returns
  resources :return_details
  resources :temp_products
  resources :temp_inventory_details

  resources :roles
  resources :role_permissions
  resources :merchant_account_roles
  resources :merchant_account_permissions
  resources :merchant_account_permission_details
  resources :permissions
  resources :permission_details

  resources :mackay_profiles
  resources :mackay_families
  resources :mackay_educations
  resources :mackay_personals
  resources :mackay_children
  resources :mackay_life_styles
  resources :mackay_hobbies
  resources :mackay_careers
  resources :mackay_and_companies

  resources "merchantAccounts", :controller => :merchant_accounts, :as => :merchant_accounts
  resources "productSummaries", :controller => :product_summaries, :as => :product_summaries

end

app/models/role_permission.rb
class RolePermission < ActiveRecord::Base

  belongs_to :role
  belongs_to :permission
end

app/controllers/role_permissions_controller.rb
class RolePermissionsController < ApplicationController
  before_action :set_role_permission, only: [:show, :edit, :update, :destroy]

  # GET /role_permissions
  # GET /role_permissions.json
  def index
    @role_permissions = RolePermission.all
    respond_to do |format|
      format.html
      format.json { render :json => @role_permissions }
    end
  end

  # GET /role_permissions/1
  # GET /role_permissions/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render :json => @role_permission }
    end
  end

  # GET /role_permissions/new
  def new
    @role_permission = RolePermission.new
  end

  # GET /role_permissions/1/edit
  def edit
  end

  # POST /role_permissions
  # POST /role_permissions.json
  def create
    @role_permission = RolePermission.new(role_permission_params)

    respond_to do |format|
      if @role_permission.save
        update_merchant_role_permission_text(@role_permission)
        format.html { redirect_to @role_permission, notice: 'Role permission was successfully created.' }
        format.json { render action: 'show', status: :created, location: @role_permission }
      else
        format.html { render action: 'new' }
        format.json { render json: @role_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /role_permissions/1
  # PATCH/PUT /role_permissions/1.json
  def update
    respond_to do |format|
      if @role_permission.update(role_permission_params)
        update_merchant_role_permission_text(@role_permission)

        format.html { redirect_to @role_permission, notice: 'Role permission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @role_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /role_permissions/1
  # DELETE /role_permissions/1.json
  def destroy
    @role_permission.destroy
    update_merchant_role_permission_text(@role_permission)
    respond_to do |format|
      format.html { redirect_to role_permissions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role_permission
      @role_permission = RolePermission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_permission_params
      params.require(:role_permission).permit(:role_id, :permission_id)
    end


end

app/helpers/role_permissions_helper.rb
module RolePermissionsHelper
end

app/views/role_permissions/_form.html.haml
= form_for @role_permission do |f|
  - if @role_permission.errors.any?
    #error_explanation
      %h2= "#{pluralize(@role_permission.errors.count, "error")} prohibited this role_permission from being saved:"
      %ul
        - @role_permission.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :role_id
    = f.number_field :role_id
  .field
    = f.label :permission_id
    = f.number_field :permission_id
  .actions
    = f.submit 'Save'

app/views/role_permissions/edit.html.haml
%h1 Editing role_permission

= render 'form'

= link_to 'Show', @role_permission
\|
= link_to 'Back', role_permissions_path

app/views/role_permissions/index.html.haml
%h1 Listing role_permissions

%table
  %tr
    %th Role
    %th Permission
    %th
    %th
    %th

  - @role_permissions.each do |role_permission|
    %tr
      %td= role_permission.role_id
      %td= role_permission.permission_id
      %td= link_to 'Show', role_permission
      %td= link_to 'Edit', edit_role_permission_path(role_permission)
      %td= link_to 'Destroy', role_permission, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Role permission', new_role_permission_path

app/views/role_permissions/new.html.haml
%h1 New role_permission

= render 'form'

= link_to 'Back', role_permissions_path

app/views/role_permissions/show.html.haml
%p#notice= notice

%p
  %b Role:
  = @role_permission.role_id
%p
  %b Permission:
  = @role_permission.permission_id

= link_to 'Edit', edit_role_permission_path(@role_permission)
\|
= link_to 'Back', role_permissions_path