config/routes.rb
Zeprj::Application.routes.draw do
  root :to => 'home#welcomes', as: 'welcomes'
  get 'welcome', :to => 'home#welcome', as: 'welcome'
  get 'signin', :to => 'sessions#new', as: 'signin'
  get 'signout', :to => 'sessions#destroy', as: 'signout'
  get 'signup', :to => 'accounts#new', as: 'signup'

  get 'warehouse/home', :to => 'warehouse#home'

  resources :accounts
  resources :sessions
  resources :products
  resources :merchants

  get 'warehouses/available', :to => 'warehouses#available'
  get 'product_summaries/import_availables', :to => 'product_summaries#import_availables'
  get 'productSummaries/import_availables', :to => 'product_summaries#import_availables'

  get 'areas/showAllCustomers', :to => 'areas#showAllCustomers'
  get 'areas/showAllCustomers/:id', :to => 'areas#showAllCustomers'
  get 'warehouses/search', :to => 'warehouses#search'
  get 'product_summaries/search', :to => 'product_summaries#search'
  get 'orders/bill_code', :to => 'orders#bill_code'

  resources :gera_accounts
  resources :gera_areas
  resources :gera_customers
  resources :areas
  resources :agencies
  resources :merchant_accounts
  resources :customers

  resources :branches
  resources :warehouses
  resources :skulls
  resources :providers
  resources :product_summaries
  resources :metro_summaries

  resources :imports
  resources :deliveries
  resources :exports
  resources :export_details
  resources :inventories
  resources :inventory_details
  resources :orders
  resources :order_details
  resources :returns
  resources :return_details
  resources :temp_products
  resources :temp_inventory_details

  resources :roles
  resources :role_permissions
  resources :merchant_account_roles
  resources :merchant_account_permissions
  resources :merchant_account_permission_details
  resources :permissions
  resources :permission_details

  resources :mackay_profiles
  resources :mackay_families
  resources :mackay_educations
  resources :mackay_personals
  resources :mackay_children
  resources :mackay_life_styles
  resources :mackay_hobbies
  resources :mackay_careers
  resources :mackay_and_companies

  resources "merchantAccounts", :controller => :merchant_accounts, :as => :merchant_accounts
  resources "productSummaries", :controller => :product_summaries, :as => :product_summaries

end

app/controllers/permission_details_controller.rb
class PermissionDetailsController < ApplicationController
  before_action :set_permission_detail, only: [:show, :edit, :update, :destroy]

  # GET /permission_details
  # GET /permission_details.json
  def index
    @permission_details = PermissionDetail.all
  end

  # GET /permission_details/1
  # GET /permission_details/1.json
  def show
  end

  # GET /permission_details/new
  def new
    @permission_detail = PermissionDetail.new
  end

  # GET /permission_details/1/edit
  def edit
  end

  # POST /permission_details
  # POST /permission_details.json
  def create
    @permission_detail = PermissionDetail.new(permission_detail_params)

    respond_to do |format|
      if @permission_detail.save
        format.html { redirect_to @permission_detail, notice: 'Permission detail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @permission_detail }
      else
        format.html { render action: 'new' }
        format.json { render json: @permission_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permission_details/1
  # PATCH/PUT /permission_details/1.json
  def update
    respond_to do |format|
      if @permission_detail.update(permission_detail_params)
        format.html { redirect_to @permission_detail, notice: 'Permission detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @permission_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permission_details/1
  # DELETE /permission_details/1.json
  def destroy
    @permission_detail.destroy
    respond_to do |format|
      format.html { redirect_to permission_details_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission_detail
      @permission_detail = PermissionDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_detail_params
      params.require(:permission_detail).permit(:permission_id, :name)
    end
end

app/helpers/permission_details_helper.rb
module PermissionDetailsHelper
end

app/views/permission_details/_form.html.haml
= form_for @permission_detail do |f|
  - if @permission_detail.errors.any?
    #error_explanation
      %h2= "#{pluralize(@permission_detail.errors.count, "error")} prohibited this permission_detail from being saved:"
      %ul
        - @permission_detail.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :permission_id
    = f.number_field :permission_id
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/permission_details/edit.html.haml
%h1 Editing permission_detail

= render 'form'

= link_to 'Show', @permission_detail
\|
= link_to 'Back', permission_details_path

app/views/permission_details/index.html.haml
%h1 Listing permission_details

%table
  %tr
    %th Permission
    %th Name
    %th
    %th
    %th

  - @permission_details.each do |permission_detail|
    %tr
      %td= permission_detail.permission_id
      %td= permission_detail.name
      %td= link_to 'Show', permission_detail
      %td= link_to 'Edit', edit_permission_detail_path(permission_detail)
      %td= link_to 'Destroy', permission_detail, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Permission detail', new_permission_detail_path

app/views/permission_details/new.html.haml
%h1 New permission_detail

= render 'form'

= link_to 'Back', permission_details_path

app/views/permission_details/show.html.haml
%p#notice= notice

%p
  %b Permission:
  = @permission_detail.permission_id
%p
  %b Name:
  = @permission_detail.name

= link_to 'Edit', edit_permission_detail_path(@permission_detail)
\|
= link_to 'Back', permission_details_path